### PR TITLE
removed biz cat

### PR DESCRIPTION
**Pull request by coburnicus**
remove biz cat from external-script and package

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
This’ll definitely work & remove it. We can await some :+1:s from folks.

**Comment by jeffbyrnes** [comment]
@coburnicus also, it’ll deploy as soon as it merges. Yay Heroku.

**Comment by coburnicus** [comment]
THE DAY IS MINE

**Comment by jayroh** [comment]
:+1: from me

**Comment by tclancy** [comment]
:+1:

**Comment by mkivikoski** [comment]
:+1: death to the cat.

**Pull request merged**
